**Project**
**Portfolio Comparison and Optimization**

In [6]:
# loading data from yahoo finance
import yfinance as yf
import pandas as pd
import numpy as np

tickers= ["BLK", "JPM", "UBS"]
data = yf.download(tickers, start="2020-01-01", end="2023-12-31")
data.head()

C:\Users\dhair\AppData\Local\Temp\ipykernel_50868\1493497951.py:7: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(tickers, start="2020-01-01", end="2023-12-31")
[*********************100%***********************]  3 of 3 completed

In [7]:
data.head()

Price            Close                               High              \
Ticker             BLK         JPM        UBS         BLK         JPM
Date
2020-01-02  444.427826  120.154671  10.614063  445.318453  120.163195
2020-01-03  439.704010  118.569077  10.441544  442.437047  119.331881
2020-01-06  440.079437  118.474792  10.416899  440.751771  118.509083
2020-01-07  442.891083  116.460648  10.630494  445.161339  118.157671
2020-01-08  442.786346  117.369186  10.770152  445.440802  117.917720

Price                         Low                               Open  \
Ticker            UBS         BLK         JPM        UBS         BLK
Date
2020-01-02  10.614063  440.882744  118.596210  10.408683  445.318453
2020-01-03  10.490835  437.913988  117.489155  10.392252  438.088634
2020-01-06  10.433329  435.285723  116.992040  10.334746  436.735195
2020-01-07  10.667463  439.101513  116.409225  10.567237  439.101513
2020-01-08  10.803013  438.542709  116.220696  10.720861  443.371358

Price                              Volume
Ticker             JPM        UBS     BLK       JPM      UBS
Date
2020-01-02  119.047566  10.433328  560400  10803700  3352200
2020-01-03  117.849129  10.416898  337300  10386800  2627400
2020-01-06  117.043463  10.351177  411300  10259000  2318500
2020-01-07  117.660561  10.614064  453900  10531300  4237600
2020-01-08  116.306397  10.737291  726500   9695300  3363200

In [8]:
data.describe()

Price         Close                                   High               \
Ticker          BLK          JPM          UBS          BLK          JPM
count   1006.000000  1006.000000  1006.000000  1006.000000  1006.000000
mean     638.544974   121.735630    15.355350   645.399000   123.006861
std      117.761759    22.030536     4.425896   117.645838    21.912604
min      288.063690    67.735405     6.284643   312.082183    71.780846
25%      565.810745   106.198652    12.702973   573.415214   107.553776
50%      642.129639   126.417027    14.936596   648.912289   127.589759
75%      711.059723   139.063416    17.963201   717.461293   140.181177
max      883.062439   163.672073    29.434223   884.580416   164.046893

Price                        Low                                   Open  \
Ticker          UBS          BLK          JPM          UBS          BLK
count   1006.000000  1006.000000  1006.000000  1006.000000  1006.000000
mean      15.477334   631.530250   120.451129    15.224476   638.450526
std        4.443223   117.935177    22.093230     4.402009   117.986282
min        6.646113   285.037112    65.918389     6.144984   307.313610
25%       12.775086   558.022753   105.310500    12.602450   564.616478
50%       15.028901   637.044258   124.809777    14.814203   643.326196
75%       18.155931   702.235850   137.694379    17.727533   708.720358
max       29.627683   874.718033   163.028149    29.174704   883.089735

Price                                   Volume
Ticker          JPM          UBS           BLK           JPM           UBS
count   1006.000000  1006.000000  1.006000e+03  1.006000e+03  1.006000e+03
mean     121.732923    15.348337  7.372394e+05  1.415204e+07  3.271879e+06
std       21.985446     4.411719  6.186992e+05  7.333880e+06  2.252160e+06
min       69.903828     6.153199  1.733000e+05  3.220500e+06  6.185000e+05
25%      106.410380    12.683306  4.831500e+05  9.345700e+06  2.014125e+06
50%      126.998266    14.927525  6.166500e+05  1.225075e+07  2.734450e+06
75%      139.083132    17.947624  8.230750e+05  1.619710e+07  3.877950e+06
max      163.383744    29.339854  1.180410e+07  5.441880e+07  4.063450e+07

In [ ]:
data.to_csv(r""C:\Users\dhair\bootcamp_dhairya_gouchwal\project\data\raw"